In [1]:
print('Hello')

Hello


In [ ]:
# Numpy is the python library which is used for scientic calculation..and this is basically made for the working the arrays..

In [ ]:
# !pip install numpy installing the numpy -> 

In [2]:
import numpy as np 

In [3]:
print(np.__version__)

1.26.4


In [ ]:
# 1D array -> [1,2,3,4,5]
# 2D array -> [[1,2,3,4], [5,6,7]]

In [5]:
arr = np.array([1,2,3,4])
print(arr)

type(arr)

[1 2 3 4]


numpy.ndarray

In [6]:
# np.zeros() -> matrix n * m dimension -> 3 * 3

zero_array = np.zeros((3,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Creating the ones matrix 
ones_array = np.ones((3,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# creating array of a range 
my_arr = np.arange(1,6)
print(my_arr)

[1 2 3 4 5]


In [11]:
# Creating a 1d array using lispace
arr2 = np.linspace(1, 5, 10)
print(arr2)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [12]:
# Creating 2d Array using numpy
arr3 = np.array([[1,2,3], [4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [ ]:
li = [[1,2,3], [3,4,5], [6,7,8]]
my_2d_arr = np.array(li)
print(my_2d_arr)
type(my_2d_arr)


[[1 2 3]
 [3 4 5]
 [6 7 8]]


numpy.ndarray

In [16]:
# Creating a 2d array with zeros 
zero_arr = np.zeros((3,4))
print(zero_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
import numpy as np
arr = np.array([[[1,2,3], [3,4,5]],[[6,7,8], [8, 9, 10]] ])
print(arr)

[[[ 1  2  3]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 8  9 10]]]


In [18]:
li2 = [[[1,2,3], [3,4,5]],[[6,7,8], [8, 9, 10]] ]
arr_3d = np.array(li2)
type(arr_3d)

numpy.ndarray

In [19]:
random_value_arr = np.random.rand(2, 3, 3)
print(random_value_arr)

[[[0.91025678 0.95142548 0.81938695]
  [0.09783118 0.62795609 0.28822335]
  [0.58863605 0.84697055 0.70360473]]

 [[0.67994361 0.53508235 0.5168178 ]
  [0.276446   0.04866556 0.24289013]
  [0.46217812 0.77157937 0.92896476]]]
